# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [159]:

  import numpy as np



#### 1) Create a null vector of size 10 (★☆☆)

In [160]:
# prompt: Create a null vector of size 10

Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [161]:
Z = np.zeros((10,10))
Z.size*Z.itemsize


800

#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [162]:
Z = np.zeros(10)
Z[4] = 1
Z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [163]:
Z = np.arange(20,81)
Z


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [164]:
Z = np.arange(50)
Z = Z[::-1]
Z


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [165]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [166]:
Z = np.nonzero([1,2,0,0,4,0])
Z

(array([0, 1, 4]),)

#### 8) Create a 3x3 identity matrix (★☆☆)

In [167]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

In [168]:
Z = np.random.random((3,3,3))
Z

array([[[0.01260194, 0.947086  , 0.78485042],
        [0.72362763, 0.96612245, 0.6405737 ],
        [0.27586968, 0.14842426, 0.84553966]],

       [[0.85251618, 0.00576306, 0.94558627],
        [0.20408671, 0.50458456, 0.87774716],
        [0.77917602, 0.37195134, 0.69428297]],

       [[0.07112392, 0.52800573, 0.92756554],
        [0.75823321, 0.20270137, 0.98526106],
        [0.15077842, 0.68527639, 0.05039384]]])

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [169]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

(np.float64(0.0129021513158869), np.float64(0.9976400086894942))

#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

In [170]:
Z = np.random.random(30)
m = Z.mean()
v = Z.var()
m,v

(np.float64(0.5072037747040484), np.float64(0.10165349935458376))

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [171]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [172]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [173]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

In [174]:
Z = np.diag(1+np.arange(5))
#Z = np.diag(1+np.arange(5),k=-1)
Z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [175]:
#Z = np.zeros((8,8),dtype=int)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

In [176]:
x = np.unravel_index(50, (5,6,7))
x
# 1 ,1 ,1

(np.int64(1), np.int64(1), np.int64(1))

#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

In [177]:
a = [[1, 2],[3, 4], [5,6], [7,8]]

b = [[4, 1, 2], [2, 2, 1]]

np.dot(a, b)

array([[ 8,  5,  4],
       [20, 11, 10],
       [32, 17, 16],
       [44, 23, 22]])

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [178]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 20. How to find common values between two arrays? (★☆☆)

In [179]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z = np.intersect1d(Z1,Z2)
Z

#Method 2
#common_values = [val for val in np.unique(Z1) if val in Z2]  # Using list comprehension
#Z = np.array(common_values) #converting to numpy array

array([1, 4])

#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [180]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

print(A)

[-1.5 -1.5 -1.5]


#### 22) Extract the integer part of a random array (★★☆)

In [181]:
Z = np.random.uniform(0,10,10)
Z = Z.astype(int)
Z


array([4, 3, 0, 4, 9, 0, 2, 4, 6, 3])

#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [182]:
Z = np.zeros((5,5))
for i in range(5):
    Z[i] = i
Z

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [183]:
Z = np.random.randint(0,10,10)
Z

array([5, 7, 8, 8, 7, 5, 3, 5, 6, 8])

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [184]:
Z = np.linspace(0,1,11)[1:-1]
Z

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26) Create a random vector of size 10 and sort it (★★☆)

In [185]:
np.sort(np.random.random(10))

array([0.15312314, 0.17680867, 0.23882767, 0.33296535, 0.41345203,
       0.43555121, 0.53496396, 0.62184174, 0.85324292, 0.90039214])

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [186]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A,B)


False

#### 28) Make an array immutable (read-only) (★★☆)

In [187]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [235]:
Z = np.random.random(10)
Z = np.where(Z == Z.max(), 0, Z)
Z

array([0.25934471, 0.        , 0.65673525, 0.36961197, 0.3958432 ,
       0.4371095 , 0.07064477, 0.00470697, 0.77869013, 0.63538439])

#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [251]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [190]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), 3), 1)


Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 32) Subtract the mean of each row of a matrix (★★☆)

In [254]:
X = np.random.rand(5, 10)
X = X - X.mean(axis=1, keepdims=True)
X


array([[ 0.28860875, -0.50455622, -0.45375012,  0.10579014, -0.10475596,
        -0.11903223,  0.4042811 ,  0.26527344,  0.13270092, -0.01455983],
       [-0.11140181,  0.17597982,  0.31013936,  0.30168736, -0.4836145 ,
        -0.12659447,  0.2523414 , -0.29256827,  0.19339108, -0.21935998],
       [-0.36151412, -0.54652196, -0.04692884,  0.22972042,  0.40736638,
        -0.45673752,  0.38447001,  0.36259693,  0.27043954, -0.24289085],
       [ 0.198087  , -0.20231516,  0.14100954, -0.24060492,  0.32954425,
        -0.21462919,  0.23450208, -0.27078672,  0.25349273, -0.22829961],
       [ 0.18367698, -0.32815103, -0.28835245, -0.27807807, -0.03188253,
         0.27142745,  0.4301862 ,  0.3510222 , -0.32361267,  0.0137639 ]])

#### 33) sort an array by the 1st column? (★★☆)

In [263]:
Z = np.random.randint(0,10,(3,3))
Z = Z[Z[:,0].argsort()]
Z

array([[0, 2, 1],
       [7, 6, 7],
       [9, 7, 4]])

#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [265]:
Z = np.random.uniform(0,1,10)
z = 0.5
Z = Z[np.abs(Z - z).argmin()]
Z

np.float64(0.4863956857928725)

#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [266]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [270]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [288]:
Z = np.random.randint(0,2,(6,3))
np.unique(Z, axis=0)

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 1]])