# Recalling Numpy Array Slicing and Indexing

In [153]:
import numpy as np

In [154]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [155]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np01.png?raw=1">

In [156]:

x[0][:3]

array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np02.png?raw=1">

In [157]:
x.flatten()[:8]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Skip every other element

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np03.png?raw=1">

In [158]:
x.flatten()[:5:2]

array([1, 3, 5], dtype=int8)

## Slice first column

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np04.png?raw=1">

In [159]:
x[:4,0]

array([ 1,  6, 11, 16], dtype=int8)

## Slice a diagonal

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np05.png?raw=1">

In [160]:
np.diag(x)

array([ 1,  7, 13, 19, 25], dtype=int8)

## Repeat the first element

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np06.png?raw=1">

In [161]:
np.repeat(x[0][0],5)

array([1, 1, 1, 1, 1], dtype=int8)

## Simple 2D slicing

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np07.png?raw=1">

In [162]:
#np.indices()
x[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

## Slice a zigzag

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np08.png?raw=1">

In [178]:
np.concat((np.diagonal(x[:4],0).reshape(4,1),np.diagonal(x,1).reshape(4,1)),axis=1)

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]], dtype=int8)

## Sparse slicing

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np09.png?raw=1">

In [ ]:
x[::2,::2]

## Transpose a 2D array

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np10.png?raw=1">

In [ ]:
np.transpose(x[:3,:3])

## Repeat the first column 4 times


<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np11.png?raw=1">

In [ ]:
np.repeat(x[::,0],4).reshape(5,4)

## Reshape 1D array to 2D array

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np12.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int64)
print(x)
np.reshape(x,(4,3))

## Collapse an axis from a 3D array

<img src="https://github.com/MrEwdew/DataEng25/blob/main/week_1/IMG/np13.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)
np.reshape(x,(3,4))
